<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>download-model</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetTtsWrapper" Version="1.1.1" />
  </ItemGroup>

</Project>
