//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceGarden.UI.Resources {
    using System;

    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoiceGarden.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AppName => ResourceManager.GetString("AppName", resourceCulture);
        internal static string AdapterInstallation => ResourceManager.GetString("AdapterInstallation", resourceCulture);
        internal static string VoiceEngines => ResourceManager.GetString("VoiceEngines", resourceCulture);
        internal static string OfflineVoices => ResourceManager.GetString("OfflineVoices", resourceCulture);
        internal static string CloudVoices => ResourceManager.GetString("CloudVoices", resourceCulture);
        internal static string ConfigureVoices => ResourceManager.GetString("ConfigureVoices", resourceCulture);
        internal static string ManageModels => ResourceManager.GetString("ManageModels", resourceCulture);
        internal static string Advanced => ResourceManager.GetString("Advanced", resourceCulture);
        internal static string Close => ResourceManager.GetString("Close", resourceCulture);
        internal static string About => ResourceManager.GetString("About", resourceCulture);
        internal static string Install => ResourceManager.GetString("Install", resourceCulture);
        internal static string Uninstall => ResourceManager.GetString("Uninstall", resourceCulture);
        internal static string Register => ResourceManager.GetString("Register", resourceCulture);
        internal static string Reregister => ResourceManager.GetString("Reregister", resourceCulture);
        internal static string Validate => ResourceManager.GetString("Validate", resourceCulture);
        internal static string FetchVoices => ResourceManager.GetString("FetchVoices", resourceCulture);
        internal static string InstallSelected => ResourceManager.GetString("InstallSelected", resourceCulture);
        internal static string DownloadSelected => ResourceManager.GetString("DownloadSelected", resourceCulture);
        internal static string InstallAllToSAPI => ResourceManager.GetString("InstallAllToSAPI", resourceCulture);
        internal static string Back => ResourceManager.GetString("Back", resourceCulture);
        internal static string OpenLogs => ResourceManager.GetString("OpenLogs", resourceCulture);
        internal static string OpenModelsFolder => ResourceManager.GetString("OpenModelsFolder", resourceCulture);
    }
}
